twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel 
        timeout : 0.5
        priority: 10
      joystick:
        topic   : diff_cont/cmd_vel_unstamped 
        timeout : 0.5
        priority: 100